### PR TITLE
Optimize png images with pingo 0.63

### PR DESCRIPTION
**Pull request by bakawun**
2 pass optimization
first on auto (no arguments)
second on best (-s4)

http://css-ig.net/pingo

### CODE REVIEW

**Comment by bakawun** [comment]
pingo font6x8.png

  pingo - auto (0.01 sec):
  ---------------------------------------------------
  1 file => 0.25 KB - (34.30%) saved
  ---------------------------------------------------
  
pingo -s4 font6x8.png

  pingo - best (0.02 sec):
  ---------------------------------------------------
  1 file => 0.04 KB - (9.04%) saved
  ---------------------------------------------------
  
  

pingo hbmenu_banner.png

  pingo - auto (0.12 sec):
  ---------------------------------------------------
  1 file => 5.99 KB - (53.03%) saved
  ---------------------------------------------------

pingo -s4 hbmenu_banner.png

  pingo - best (0.35 sec):
  ---------------------------------------------------
  1 file => 0.15 KB - (2.76%) saved
  ---------------------------------------------------

**Comment by WinterMute** [comment]
What purpose does this serve?

**Comment by tetsuo55** [comment]
space savings in the repo, smaller size of the .nds and possibly a tiny reduction in loading time.

**Comment by bakawun** [comment]
it reduced the size of the images thus saving space on both the repo and in the nds file. The images can be loaded slightly quicker too.

**Comment by fincs** [comment]
This has the opposite effect, by effectively *adding* more blob objects to the Git repo to represent the "new" optimized versions of the pngs and therefore increasing the overall repo size. Moreover, the images are converted to DS native formats during the build stage so not even a single bit changes in the final compiled binary.

**Comment by bakawun** [comment]
well if its not used in the nds then its pointless

**Pull request closed without merging**
